### ISSUE TITLE
Version number is in too many places

### ISSUE THREAD

**Issue by ceball** [ioam/param#102]
```
param/__init__.py (twice)
numbergen/__init__.py
setup.py
```

**Comment by ceball** [comment]
Oh yeah, not to mention in the git tag itself too.

**Comment by ceball** [comment]
Ok, I was joking a bit - I don't really want to reopen the version debate ;) 

I accept the git tag & package/init.py duplication. 

Param has numbergen and param so that duplication is also ok.

I should be able to avoid having to manually set setup.py's version, though. This issue is here as a reminder to address that.

**Comment by jlstevens** [comment]
> Ok, I was joking a bit - I don't really want to reopen the version debate ;)

I knew you were just trying to wind me up which is why I ignored you. ;-p

The version string in ``setup.py`` is the only once I find annoying (but unavoidable iirc). At least the  ``__version__.verify`` will make sure it is set correctly before uploading to PyPI!

**Comment by jbednar** [comment]
If I were doing it, I would write a short Python function or script to do the updating for me. Nothing as complicated as versioneer, just a simple search and replace, and then put it on IOAM somewhere.

**Comment by jbednar** [comment]
Fixed using the version.py class.
