### ISSUE TITLE
String does not set allow_None=True for default of None

### ISSUE THREAD

**Issue by ceball** [ioam/param#104]
Setting `allow_None`:
https://github.com/ioam/param/blob/master/param/parameterized.py#L526

**Comment by jbednar** [comment]
Can't that just safely be deleted, along with the explicit argument?

**Comment by philippjfr** [comment]
Hmm, is it really redundant though? Parameter sets:

```
        self.allow_None = (default is None or allow_None)
```

Do we want this behavior for String?

**Comment by jbednar** [comment]
I can't think of any reason why not.  The current logic doesn't do that, but it doesn't have a comment saying why it works in this strange way, which makes me think it wasn't intentional.
