### ISSUE TITLE
Add a convenience method to allow multiple parameters to be set?

### ISSUE THREAD

**Issue by ceball** [ioam/param#108]

**Comment by jbednar** [comment]
Jean-Luc implemented that for the specific case we were using:

```python
def __call__(self, **kwargs):
    """Convenience method for setting multiple parameters using keywords."""
    for k, v in kwargs.items():
        self.set_param(k,v)
```

But this is something that would be useful for any Parameterized object, so I would like to avoid implementing it just for our one class.  I suspect that stealing ``__call__`` to do so is not a good idea in general, since some Parameterized classes probably have their own implementation of that, but we could add the above as a new method for Parameterized, e.g. ``set_params``.

Alternatively, we could change the existing Parameterized.set_param to accept keywords:

```python
@bothmethod
def __call__(self_or_cls, param_name=None, val=None, **kwargs):
    if param_name is not None:
        kwargs[param_name]=val

    for (k,v) in kwargs.items():
          if k not in self_or_cls.params():
               raise ValueError("'%s' is not a parameter of %s"%(k,self_or_cls))
          setattr(self_or_cls,k,v)
```

Would either of those options be ok to add right now?

**Comment by ceball** [comment]
I agree about not using ``__call__``. I also like the idea of not having ``set_param`` and ``set_params``. I assume the second option above is supposed to be ``set_param`` not ``__call__``. I think extending ``set_param`` as above isn't a bad idea, but with the code above isn't it possible for me to do e.g. ``.set_param('x',100,x=200)`` and get ``x`` set to ``100``? If I'm right about that, I'd probably prefer to see an error in that case.

**Comment by jbednar** [comment]
In that case, how about:

```python
@bothmethod
def __call__(self_or_cls, param_name=None, val=None, **kwargs):
    if param_name is not None:
        if param_name in kwargs:
             raise ValueError("'%s' supplied as both positional and keyword argument to %s" % 
                                        (k,self_or_cls.name))
        kwargs[param_name]=val

    for (k,v) in kwargs.items():
          if k not in self_or_cls.params():
               raise ValueError("'%s' is not a parameter of %s"%(k,self_or_cls.name))
          setattr(self_or_cls,k,v)
```

**Comment by jbednar** [comment]
I just realized that since this is a @bothmethod, this provides a handy way to set several class parameters at the same time as well.  That will be useful for .ty files!

**Comment by ceball** [comment]
Also this assumes there'll never be a parameterized with parameters called ``param_name`` or ``val``. They do both seem like bad parameter names so maybe I shouldn't worry! 

I suppose the only alternative is ``set_param(self_or_cls, *args, **kw)`` with args having to be either empty or length 2, but methods like that aren't easy to use. 

So for simplicity I think I'd prefer a new method rather than extending ``set_param``, and make ``set_param`` call that new method (and add ``set_param`` to the list of things we'd like to remove). But I would be ok with your suggestion, accepting that anyone using parameters called ``param_name`` and ``val`` should be used to dealing with confusion anyway...

**Comment by jbednar** [comment]
Good point.  Why do you say that methods like that aren't easy to use?  In this case we would henceforth suggest that people always use the keyword form, which is plenty easy, and thus the positional arguments would only be for backwards compatibility.

**Comment by ceball** [comment]
Ah, of course, nobody would need to be instructed about how to use the ``*args`` bit - it would just be for existing code to keep working and for people who are already used to using it that way (if it's something they type in interactively). So no problem.

**Comment by jbednar** [comment]
Ok, I'll add that, test it out, and commit if there are no problems.

**Comment by jbednar** [comment]
Ok, I've committed that in 6d1f45d.  It accepts a single pair of positional arguments, or a list of keywords, but not both (to avoid confusion). I've tested that it works ok on both classes and objects; seems very useful.
