### ISSUE TITLE
Param *almost* works on pypy

### ISSUE THREAD

**Issue by jlstevens** [ioam/param#111]
I have heard from a reliable source that param (maybe not numbergen) _almost_ works on pypy. :-)

The only thing that needs to be changed is how we register numpy RandomState with [script_repr](https://github.com/ioam/param/blob/master/param/parameterized.py#L914-L915). The official numpy version that is currently available for pypy lacks `RandomState` so instead of an `ImportError` you get an `AttributeError`.

One fix is to change `except ImportError:` to simply `except:` without trying to catch any particular exception. Although not completely ideal, this might be worth considering if anyone wants to use param with pypy.

**Comment by timsnyder** [comment]
We're getting more and more interested in pypy, so this might be of use for me.  Thanks for filing the ticket so that I could see that this is out there.

**Comment by timsnyder** [comment]
Looks like the import of numpy has been changed to have an empty `except:` already as of [6334350](https://github.com/ioam/param/blob/633435009325fd10734301aac78cd19dc7f860e9/param/__init__.py#L52-L56)

**Comment by jlstevens** [comment]
Based on my original notes, that suggests param should be working with pypy. @timsnyder Could you confirm? If not I'll set up pypy and try it myself...

**Comment by philippjfr** [comment]
pypy is already in the travis test matrix: https://travis-ci.org/ioam/param/jobs/226012979

**Comment by jlstevens** [comment]
I forgot that was added! Looks like this issue can be closed.

**Comment by jlstevens** [comment]
Though perhaps ``RandomState`` is still an issue and is simply not tested. So we might need to look out for that...
