### ISSUE TITLE
Replace home page's manual changelog list with GitHub Releases

### ISSUE THREAD

**Issue by svetlyak40wt** [ioam/param#117]
Hi! Yesterday somebody added this python library to my release notes tracking service allmychanges.com: https://allmychanges.com/p/python/param/

But service discoveredy only one 1.3.2 version and he took it from GH Releases: https://github.com/ioam/param/releases

I've tuned the package at allmychanges to search data in a repository and it found a changelog in the  [doc/index.rst](https://github.com/ioam/param/blob/master/doc/index.rst) file. And this changelog is much longer.

Which source should AllMyChanges use? Are you going to switch to GitHub's Releases instead of a file?

**Comment by jbednar** [comment]
The changelog in doc/index.rst is currently the master version.  The first entry is from 2012 (and it carried over from another project that first released in 2005), so it predates Github's support for explicitly tracking releases.  For now, you should use the doc/index.rst list, but it would be useful to switch to use Github's explicit support, which links everything up better.  For that reason, I'll change the title of this issue to make it a to-do item, though I'm not sure when we can get to it.  Thanks for the heads up!

**Comment by svetlyak40wt** [comment]
@jbednar if you are planing to write all future releases in GitHub, then I can point AllMyChanges to it and it will keep all history which already taken from a file, but info about new releases will pull from GitHub Releases.

**Comment by jbednar** [comment]
That's probably your safest bet, since GitHub Releases will always at least have the release number listed, and should have the rest of the description as well as long as we get on top of this by then.
