### ISSUE TITLE
Python3 support 

### ISSUE THREAD

**Issue by pathcl** [ioam/param#141]
There are weird inconsistencies regarding exception handling:

> rumanio:ezmomi cosmonautas$ pip3 list |grep -i params
> params (0.2.1)
> 
> rumanio:ezmomi cosmonautas$ grep -r -i except /usr/local/lib/python3.6/site-packages/params/
> Binary file /usr/local/lib/python3.6/site-packages/params//contrib/__pycache__/django.cpython-36.pyc matches
> Binary file /usr/local/lib/python3.6/site-packages/params//contrib/__pycache__/tornado.cpython-36.pyc matches
> /usr/local/lib/python3.6/site-packages/params//contrib/django.py:    except Exception as e:
> /usr/local/lib/python3.6/site-packages/params//contrib/tornado.py:        except Exception as e:
> /usr/local/lib/python3.6/site-packages/params//core.py:class InvalidParams(Exception):
> /usr/local/lib/python3.6/site-packages/params//core.py:            except Exception as e:
> /usr/local/lib/python3.6/site-packages/params//core.py:                except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//core.py:                        except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//core.py:            except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:            except UnicodeDecodeError:
> /usr/local/lib/python3.6/site-packages/params//fields.py:                except ValueError as e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:                except ValueError as e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:        except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:        except ValueError:

> rumanio:ezmomi cosmonautas$ python3
> Python 3.6.0 (default, Dec 24 2016, 00:01:50)
> [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>>

Why not always use 'as' ?. This breaks compatibility on python 3.6.0 at least

**Comment by jbednar** [comment]
I'd be happy to accept a pull request making them all consistently use `as`.  I'm not sure how we would be able to test it, as our tests don't have good coverage of error conditions, but as long as spot checks had been done it seems like an improvement.

**Comment by philippjfr** [comment]
I'm fairly certain this issue was about a different library called ``params``.

**Comment by pathcl** [comment]
Yes thats why I closed it :)

**Comment by jbednar** [comment]
:-)
