### ISSUE TITLE
Drop support for python 2.6?

### ISSUE THREAD

**Issue by ceball** [ioam/param#175]
I struggle to remember what's valid in all the different pythons, and thinking about it takes up time. It used to be worthwhile to support multiple versions of Python 2 while people moved between versions and when people relied on their system's python, but those days seem to be gone with everyone converging on Python 2.7 (Python 2.6 hasn't had an update since 2013; https://www.python.org/download/releases/2.6.9/). And it's not like we've kept supporting every version of Python 2 we ever used (we happily dropped 2.5, 2.4, ... etc in the past).

But please comment if you need param to keep working on Python 2.6...

**Comment by jlstevens** [comment]
Dropping Python 2.6 is fine by me...

**Comment by hugovk** [comment]
It's definitely time to drop 2.6, it's getting harder to support with other packages dropping it too. Similarly with 3.2 too.

**Comment by ceball** [comment]
(I agree that it gets harder to support python 2.6 as your dependencies start dropping it, but param has no dependencies other than python.)

**Comment by hugovk** [comment]
(I see quite a few test dependencies :)

**Comment by ceball** [comment]
If there are any dependencies other than python, that's a mistake: param shouldn't be depending on anything other than python. However, we do enable some extra (entirely optional) features if certain other packages are present (e.g. numpy, ipython).

Please let us know if you are aware of any non-optional dependencies; the automatic testing of param is not currently set up very well (e.g. #189), so something could have slipped in. Thanks!

**Comment by hugovk** [comment]
I can see things like pip, coveralls and flake8 being used on Travis CI for testing.

At least current pip 9 deprecates Python 2.6 support, pip 10 won't support it (pypa/pip#3955).

You can see deprecation warnings in the log already:

![image](https://user-images.githubusercontent.com/1324225/31610076-5fd56482-b27f-11e7-8469-2aea4d21cc3a.png)

https://travis-ci.org/ioam/param/jobs/288291115#L450

**Comment by jbednar** [comment]
I'm happy to drop Python 2.6 testing; old versions of Param will always stay around for anyone who needs to work with old Python versions.

**Comment by ceball** [comment]
> I can see things like pip, coveralls and flake8 being used on Travis CI for testing.

Speaking from a personal point of view: those are all optional things that param predates. param doesn't depend on pip (the source of the deprecation warning`*`), coveralls, flake8, travis, setuptools, or anything else: param's just two files (at most) that you can copy into your python project without needing any of the confusing, varied, ever-changing ecosystem of python packaging/testing tools.

`*` ...a deprecation warning from a python packaging tool of all things - the cheek! ;)

**Comment by hugovk** [comment]
See PR https://github.com/ioam/param/pull/203.
