### ISSUE TITLE
ParameterizedFunctions and state

### ISSUE THREAD

**Issue by ceball** [ioam/param#187]
Originally, a ParameterizedFunction was a class that you could call; an instance was created behind the scenes and existed for the duration of the call only. Then, we added `.instance()`, I *think* originally so that we could use ParameterizedFunctions in ClassSelectors (which at the time only supported instances, not classes), and maybe also so we could have different versions of a ParameterizedFunction around, with different defaults, without having to make new classes:

<img width="505" alt="screen shot 2017-09-10 at 6 16 47 pm" src="https://user-images.githubusercontent.com/1929/30251608-1a9d3e16-965b-11e7-86c7-e3c4f9300ad5.png">

Having this kind of long-lived instance of a ParameterizedFunction seems like a good idea and a bad idea to me. On the plus side it's convenient, and seems to be used in a few places in topographica, imagen, and holoviews. Param is supposed to be practical and useful for improving code that's using it, after all - more of a goal than theoretical purity and simplicity. However, I guess I do get a bit surprised/concerned by the stage of something called a 'function' having state...somehow even if I have just immediately before written `.instance()`. Am I worrying about nothing? Here's a really contrived example of two generators using the same hv Operation(ParameterizedFunction) instance, and interfering, to try to demonstrate what I feel unease about:

<img width="621" alt="screen shot 2017-09-10 at 6 49 47 pm" src="https://user-images.githubusercontent.com/1929/30251625-59fe5504-965b-11e7-997a-fb874a378346.png">

This happens because Operation sets `self.p = ParamOverrides(...)` in `__call__(...)` and in `process_element(...)`. Obviously the example is a bit ridiculous, but does it get my point across? If so, should I worry about it or not?

**Comment by jlstevens** [comment]
I also need to think carefully about this, but I don't *think* I am that surprised that this is happening - both ``G1`` and ``G2`` are fiddling with the same instance ``o``.

I've gotten used to the fact that ``ParameterizedFunction`` has state and I sort see them as halfway between a callable class and a normal function, or alternatively as a closures with bits of state I can manipulate (but probably shouldn't!). I view state on parameterized functions as something that is often useful but *can* be dangerous or confusing but not a problem if I am being careful.

That is just my initial reaction and I need to think a bit more about whether I consider this to be a real problem or not.

**Comment by jbednar** [comment]
It's certainly true that people could use ParameterizedFunction in a surprising and confusing way, but I don't think there's any underlying problem that we should address.  Yes, it will act like that, no, people probably shouldn't do that, but if they do, I don't think I'd want to stop it.
