### ISSUE TITLE
Simplify version-related code in setup.py and __init__.py?

### ISSUE THREAD

**Issue by ceball** [ioam/param#215]
Not sure I've got this right; do any of the following changes make sense?

## setup.py embed_version() 

Will never be called (because version.py is bundled): remove this function?

## setup.py get_setup_version()
  * two tries to import `param.version`
  * `version` will never be None (as version.py is bundled)
  * `version_file_path` will never be used

So could it be simplified to something like this?

```python
def get_setup_version(reponame):
    import param.version
    return param.version.Version.setup_version(os.path.split(__file__)[0], reponame, dirty='raise', archive_commit="$Format:%h$")
```

(Unrelated note: changed `dirty` from `strip` to `raise`. I think `report` would be ok too. I'm not sure `strip` should be an option, let alone the default - what am I missing?)

## `__init__.py`

Currently:

```python
# Determine up-to-date version information, if possible, but with a
# safe fallback to ensure that this file and parameterized.py are the
# only two required files.
try:
    from .version import Version
    _version = Version(fpath=__file__, archive_commit="$Format:%h$", reponame="param")
    __version__ = str(_version)
except:
    import json
    __version__ = json.load(open(os.path.join(os.path.split(__file__)[0],
                                              '.version'), 'r'))['version_string']
```

* For the comment to still be true, would need an "if exists .version" or one more except.
* Should probably delete names once done with them (`Version`, `json`)?
* Will the current except ever be used? Doesn't Version itself look for the .version file? I might have misunderstood...

Could it be changed to something like the following?

```python
# Determine up-to-date version information, if possible, but with a
# safe fallback to ensure that this file and parameterized.py are the
# only two required files.
try:
    from .version import Version
    _version = Version(fpath=__file__, archive_commit="$Format:%h$", reponame="param")
    __version__ = str(_version)
except:
    __version__ = '0.0.0+unknown'
```

(where 0.0.0+unknown could be whatever makes most sense for indicating version unknown)

**Comment by jbednar** [comment]
That all sounds good to me.  Do we *need* to keep _version around? It would be nice to make this as simple as possible...

**Comment by jlstevens** [comment]
This should be fine for ``__init__.py``:

```python
from .version import Version
__version__ = str(Version(fpath=__file__, archive_commit="$Format:%h$", reponame="param"))
```

For ``setup.py`` I agree we shouldn't need ``embed_version()`` but otherwise I cannot tell offhand if your suggested change is fine. I suggest trying it out and testing it.
