### ISSUE TITLE
Regular expression for 'String' Parameter?

### ISSUE THREAD

**Issue by thomasdeneux** [ioam/param#240]
Hello,
- First the 'String' Parameter sub-class is not present in the doc, and i initially thought that there is no such sub-class because i was looking in param/__init__.py instead of param/parameterized.py
- Second, a nice idea would be to add regular expression matching to the class. In fact I am trying to add this right now, will send a pull request.

**Comment by thomasdeneux** [comment]
I have now addressed the second bullet point by adding regular expression testing and submitting a pull request.

**Comment by jbednar** [comment]
Thanks!  We should make String more visible in the docs; yes, it's hard to notice in the code, because it's one of the few most basic Parameter types that we had to define in parameterized.py rather than postponing to `__init__.py`.

RegEx matching is a great feature to have, thanks!

**Comment by ceball** [comment]
Thanks for addressing this in #241.

Yes, param's docs need to be improved. It should be happening soon as part of all pyviz project documentation being improved/unified.

String's there, but hidden away: http://param.pyviz.org/Reference_Manual/param.html#param.parameterized.String. You're right that it's missing from the class diagram at the top, though.
