### ISSUE TITLE
subscriber-> watcher

### ISSUE THREAD

**Issue by jbednar** [ioam/param#273]
Right now we have a watch() mechanism, but also the notion of a "subscriber", which as far as I can see is something that watches. Can we just replace "subscriber" with "watcher", to avoid introducing a new concept of subscription unnecessarily?

**Comment by ceball** [comment]
I think we already decided that in #262.

Everyone is free to edit that issue (or otherwise close it and replace with separate issues).

**Comment by jbednar** [comment]
That one was about subscribing vs watching, and this is about subscriber vs watcher, but in any case I'm glad you agree, and Jean-Luc can now go ahead and rename it.

**Comment by jlstevens** [comment]
Reopening this issue till the PR referenced above is actually merged...
