### ISSUE TITLE
Possible incompatibility between param and autoreload IPython extension?

### ISSUE THREAD

**Issue by zbarry** [ioam/param#288]
Hi all - my investigation into https://github.com/ioam/holoviews/issues/3030 makes me think the phenomenon seen there is actually a product of what the param package does to classes that use it.

Summary of that issue is that upon changing HoloViews code of inside a class, `autoreload`'s reload of that class breaks any subsequent plotting of that element with the error posted in that issue. 

I've narrowed it down to specifically the `super()` call: changing, for example, `super(RasterPlot, self).__init__(*args, **kwargs)` in `RasterPlot` to `super().__init__(*args, **kwargs)` (which I think is Python 3 only) produces no error and the plot appears as expected. There is a warning, however, that appears:

>WARNING:root:Setting non-Parameter class attribute RasterPlot.style_opts = ['cmap', 'alpha'] 
WARNING:root:Setting non-Parameter class attribute QuadMeshPlot.style_opts = ['cmap', 'color', 'line_color', 'line_alpha', 'color', 'alpha', 'line_width', 'line_join', 'line_cap', 'line_dash', 'selection_line_color', 'nonselection_line_color', 'muted_line_color', 'hover_line_color', 'selection_line_alpha', 'nonselection_line_alpha', 'muted_line_alpha', 'hover_line_alpha', 'selection_color', 'nonselection_color', 'muted_color', 'hover_color', 'selection_alpha', 'nonselection_alpha', 'muted_alpha', 'hover_alpha', 'fill_color', 'fill_alpha', 'selection_fill_color', 'nonselection_fill_color', 'muted_fill_color', 'hover_fill_color', 'selection_fill_alpha', 'nonselection_fill_alpha', 'muted_fill_alpha', 'hover_fill_alpha'] 

Possibly adding to the fun is that adding the following to the top of `__init__()` in `RasterPlot`:

`print(type(self))` produces `<class 'holoviews.plotting.bokeh.raster.RasterPlot'>`

and

`print(type(RasterPlot))` produces `<class 'param.parameterized.ParameterizedMetaclass'>`

both the first time `__init__()` is called and the second time, after the class is `autoreload`'d. For some reason, this "discrepancy" is only a problem after the reload (referring to the `TypeError: super(type, obj): obj must be an instance or subtype of type` error).

Any idea what might be happening here? I'm not well versed on what `param` is doing under the hood.

Note that the "caveats" section of the docs of the `autoreload` extension states:

>Caveats
>
>Reloading Python modules in a reliable way is in general difficult, and unexpected things may occur. %autoreload tries to work around common pitfalls by replacing function code objects and parts of classes previously in the module with new versions. This makes the following things to work:
>
>Functions and classes imported via ‘from xxx import foo’ are upgraded to new versions when ‘xxx’ is reloaded.
>Methods and properties of classes are upgraded on reload, so that calling ‘c.foo()’ on an object ‘c’ created before the reload causes the new code for ‘foo’ to be executed.
>
>Some of the known remaining caveats are:
>
>Replacing code objects does not always succeed: changing a `@property` in a class to an ordinary method or a method to a member variable can cause problems (but in old objects only).
>Functions that are removed (eg. via monkey-patching) from a module before it is reloaded are not upgraded.
>C extension modules cannot be reloaded, and so cannot be autoreloaded.

**Comment by jlstevens** [comment]
@zbarry Thanks for tracking this issue down to param! I know autoreload is used a fair bit so I think this is relatively high priority. Unfortunately, tracking down how param's metaclass magic interacts with autoreload is going to be no easy feat...

**Comment by philippjfr** [comment]
I'd love to be able to use ``autoreload`` and always assumed this was simply a general limitation affecting any code spread across multiple modules. If this is indeed specific to param based classes then there's at least some hope that it could be made to work.

**Comment by jlstevens** [comment]
When I last looked at `autoreload` (a long time ago!) I do remember that it came with warnings saying that it might not always work...

**Comment by zbarry** [comment]
In my experience, I pretty much always have the `autoreload` magic at the top of my notebooks. For example, when I'm using notebooks to test packages I'm developing, it's pretty much set-it-and-forget-it. I can go run a cell, see there's an error in some of the package code, modify that code in my IDE & save, then run the cell again, and everything's good to go. I think if you're not doing anything funky with Python [classes?] you can basically forget you're even using it. Might have not been the case back then.

**Comment by zbarry** [comment]
Turns out this is a problem in `autoreload` after all...

https://github.com/ipython/ipython/issues/461 - see @dashesy 's comment.

Apparently I just never tried to create another instance of a subclass I've modified that called its superclass with `super(Class, obj).__init__()`... very unfortunate limitation...

There is this blog post: http://luke-campagnola.blogspot.com/2010/12/easy-automated-reloading-in-python.html that proposes its own (non-IPython) implementation for module reloading, but it's Python 2 and might take a bit of tweaking (not to mention making an IPython extension, though much of the wrapper might just be ripped from `autoreload`'s implementation itself). Shame.

**Comment by dashesy** [comment]
@zbarry there is a reason [super is considered harmful](https://fuhm.net/super-harmful/) by many, it is a hack because [you have to stick to keyword arguments too](https://stackoverflow.com/questions/1259547/is-it-a-good-idea-to-use-super-in-python), in the `__init__`, to be safe (and absolutely no multiple-inheritence)!  
You may say this is an issue with `super`, in Python explicit is always better. 
If you could change **all** those `super` calls `autoreload` will work: `Class.__init__(obj)`
