### ISSUE TITLE
Setting parameter defaults through another function

### ISSUE THREAD

**Issue by MHC03** [ioam/param#302]
I have looked into other issues and haven't found any answer to this problem. So if there really is one, I apologize.

I use parameters in combination with panel and holoviews for dashboards etc.. My problem is that most of the bounds and defaults of my params are determined by currently loaded data. That's why I somehow need a way to declare my parameter defaults without using global variables or functions. Currently I am doing it like this:
```python
def column_options(col_data: ColumnData):
    nat_pulse_filter_keys = col_data.nat_pulse_filter_keys()
    default_binning = col_data.binning
    default_column = col_data.column
    class ColumnOptions(param.Parameterized):
        nat_pulse_filter = param.ObjectSelector(default="All", objects=nat_pulse_filter_keys)
        binning = param.Integer(default=default_binning, bounds=(0, 2000))
        log10 = param.Boolean(True)
        column = param.ObjectSelector(default=default_column, objects=['m_n', 'tof'])
    return ColumnOptions(name='Options')
```

I honestly don't like this approach and I would like to know how it should normally be done. I would prefer being able to declare param attributes in \_\_init\_\_ or any other method, so that I can call my Options class and give it the needed data.

**Comment by philippjfr** [comment]
You can access and override parameter attributes at any time, e.g.:

```
    class ColumnOptions(param.Parameterized):
        nat_pulse_filter = param.ObjectSelector()
        binning = param.Integer()
        log10 = param.Boolean()
        column = param.ObjectSelector()

  ColumnOptions.params('nat_pulse_filter').objects = nat_pulse_filter_keys
  ColumnOptions.params('binning').bounds = (0, 2000)
```
