### ISSUE TITLE
ParamOverrides: create overrides attr?

### ISSUE THREAD

**Issue by sf-issues** [ioam/param#36]
Converted from SourceForge issue 2888861, submitted by ceball
Submit Date: 2009-10-29 15:43 GMT

set e.g. .overrides on Parameterized instance, and override __getattribute__ to look in .overrides first; would have to set .overrides=None after __call__. Or something like that.

**Comment by ceball** [comment]
I suppose we could do it with a decorator...

```
class Fn(param.ParameterizedFunction):
    x = param.Number(1)

    def __call__(self,**params):
        p = ParamOverrides(self,params)
        return p.x
```

could become

```
class Fn(param.ParameterizedFunction):
    x = param.Number(1)

    @add_overrides
    def __call__(self,**params):
        return self._overrides.x
```

In some future less polluting api (#154) that might be ``self.params.overrides.x`` or something.

**Comment by ceball** [comment]
I added in #92:
```
class A2(param.Parameterized):
    path = param.Path(search_paths=['/etc'])
    @overrides
    def __call__(self,**params):
        return self._overrides.path
    
a2 = A2(path=test_file)
assert a2() == test_path+test_file, a2()
assert a2(path=test_file) == test_path+test_file, a2(path=test_file)
```

What do people think?

**Comment by jlstevens** [comment]
Personally, I prefer the explicit use of ``ParamOverrides`` instead of introducing a decorator...

**Comment by sf-issues** [comment]
Same; decorator doesn't seem like an improvement.

**Comment by ceball** [comment]
Not adding this feature

**Comment by jlstevens** [comment]
Jim? Are you still logged in as sf-issues?!

**Comment by jbednar** [comment]
Yep, that's me!
