### ISSUE TITLE
Parameterized subclasses can't override parameter with method or property

### ISSUE THREAD

**Issue by philippjfr** [ioam/param#79]
This is something that has annoyed me for a long time but I have no idea how I would go about fixing it.

Any ideas, would this even be possible?

**Comment by jbednar** [comment]
Overriding a parameter with a method seems like a horrible idea, since a method has a different interface from a parameter.  A property would be ok, but I don't know how to do it.  Maybe we could write a suitable subclass of Parameter that behaves like a property (PropertyParam?), and then just declare that parameter to be of type PropertyParam?  I haven't thought it through very well, but it seems like it should work, because Parameters already control getting and setting, the main things you want to do with a property.

**Comment by philippjfr** [comment]
Yes, that seems like a reasonable solution. You'd simply define the names of the getter and a setter in the Property definition. I'll come back with prototype in a bit.

**Comment by jbednar** [comment]
Sounds good.  Maybe param.Property is the right name; not sure.  I've never thought that property was a very good name for the concept in Python, but what can one do...

**Comment by philippjfr** [comment]
Just realized I'm having the inverse problem. Overriding a parameter with a property actually seems to work just fine but overriding a property with a parameter does not. That's because there is a small bug on line 746 in ParameterizedMetaclass:

```python
if super_param is not None and super_param.instantiate is True:
```

should be:


```python
if isinstance(super_param, Parameter) and super_param.instantiate is True:
```

**Comment by jlstevens** [comment]
It's not a small bug! It is an annoying bug that has been causing us problems!

Thanks for fixing this!

**Comment by jbednar** [comment]
Seems like a reasonable fix to me for an incorrect assumption. 

Having param.Property might still make sense as a convenient way to override a Parameter without losing docstrings, softbounds, etc.; up to you.  But I'm not sure how the getters and setters would be able to access the bounds and other slots of the Parameter, so it might not really work out well.

**Comment by jlstevens** [comment]
The problem with tying parameters and properties (where parameters can wrap properties) is that properties are essentially arbitrary code and therefore might return any value (or type of value) when called. 

You could type/bounds check the return value of the property but you would have to do that on every single access (which sounds horrendously inefficient!) whereas normal parameters only need to type/bounds check when the parameter value is set. The deeper, fundamental reason is that the value of property is a function of the entire object state at any given moment which is not the case for simpler attribute-like state.

As a result I think it is best to use docstrings of property methods for documentation purposes and forget type and bounds checking (and the other things param offers) when it comes to properties.

**Comment by jbednar** [comment]
Sure, though functions returning truly arbitrary possible types of values are essentially unusable.  There's no need to type check necessarily; one could simply declare the type and then surrounding code could work with that assumption, while people have to be sure to write getters and setters that respect the type.  In any case, it doesn't sound like there's an immediate use case for this, so best not to do it.
