### ISSUE TITLE
param.String has wrong default value

### ISSUE THREAD

**Issue by ceball** [ioam/param#87]
Currently it's `None`, but it should be `''`.

**Comment by jbednar** [comment]
It used to be '', but apparently changed accidentally in the recent revisions.  I believe it's on Philipp's to do list to fix 
Jim

On February 1, 2015 5:06:19 PM GMT, Chris B <notifications@github.com> wrote:
|  Currently it's `None`, but shouldn't it be `''`?
|  
|  ---
|  Reply to this email directly or view it on GitHub:
|  https://github.com/ioam/param/issues/87
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ceball** [comment]
We don't want "on Philipp's to-do list" to become a reference like "in Chris's email", do we? ;)

**Comment by philippjfr** [comment]
Just pushed this fix. However Python 2.6 doesn't seem to like the test you added:

```
======================================================================
ERROR: test_handling_of_None (tests.testparameterizedobject.TestStringParameter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ioam/param/tests/testparameterizedobject.py", line 248, in test_handling_of_None
    with self.assertRaises(ValueError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
```

Seems like 2.6 has a different signature for assertRaises.

**Comment by jbednar** [comment]
I think Chris added that.

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ceball** [comment]
Good news: the github emails you all generate are small.
Bad news: I've unknowingly had my github email sorted by size (largest to smallest) for the last week or so, so I didn't see any of your emails!
