### ISSUE TITLE
ParameterFunction instances lack __name__

### ISSUE THREAD

**Issue by jlstevens** [ioam/param#90]
In holoviews, we often need to get hold of the name of a  ``ParameterizedFunction`` class (call it ``func``). This is normally done using ``func.__name__`` which works fine...unless you create an instance.

Once you create an instance ``__name__`` no longer exists; working around this in holoviews would be extremely awkward and unwieldy. What I want is for instances to behave in a similar way to the original parameterized function - i.e. supply ``__name__``.

In addition I would like the ability to set a new, custom name. Here is the diff to ``instance`` (in parameterized.py) that does what I want:

```diff
diff --git a/param/parameterized.py b/param/parameterized.py
index fa8ec29..92d8990 100644
--- a/param/parameterized.py
+++ b/param/parameterized.py
@@ -1719,6 +1719,8 @@ class ParameterizedFunction(Parameterized):
 
         inst=Parameterized.__new__(cls)
         Parameterized.__init__(inst,**params)
+        if 'name' in params:  inst.__name__ = params['name']
+        else:                 inst.__name__ = self_or_cls.name
         return inst
 
     def __new__(class_,*args,**params):
```

Alternatively, I can imagine changing ``instance`` so it accepts an optional argument ``instance_name``:

```python
   @bothmethod
    def instance(self_or_cls, instance_name=None, **params):
```

That way you could supply a customize name, with ``__name__`` on the instance set to the source class ``__name__`` by default (i.e. if ``instance_name`` is ``None``).

**Comment by jbednar** [comment]
That diff looks fine to me; I can't think of anywhere we are assuming that a ParameterizedFunction instance has no name.

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by jlstevens** [comment]
Comitted in 2501b49e
